### ISSUE TITLE
Data format issue 

### ISSUE THREAD

**Issue by akshatsingh22** [GitYCC/rcnn-pytorch#12]
Hi there,

Many thanks for the clean implementation...

I have a issue here, 

annotation_train.txt (example annotations)

- ./1391/4/361_Kindest_42517.jpg kindest
- ./1211/6/401_Grizzlies_33809.jpg grizzlies
- ./1833/4/74_BALDY_5595.jpg baldy

annotation_val.txt  (example annotations)

- ./2271/2/390_PATRICIA_55938.jpg patricia
- ./929/4/397_Percival_56583.jpg percival
- ./1837/5/377_REPULSIVE_64992.jpg repulsive

lexicon.txt  (example annotations)

- 0
- 00
- 002101
- 01
- 01206
- 01206368166

When I ran python src/train.py
it was giving me error -    

- index = int(index_str)
- ValueError: invalid literal for int() with base 10: 'kindest'

Then I changed -
```
    def _load_from_raw_files(self, root_dir, mode):
        mapping = {}
        with open(os.path.join(root_dir, 'lexicon.txt'), 'r') as fr:
            for i, line in enumerate(fr.readlines()):
                mapping[i] = line.strip()
        paths_file = None
        if mode == 'train':
            paths_file = 'annotation_train.txt'
        elif mode == 'dev':
            paths_file = 'annotation_val.txt'
        elif mode == 'test':
            paths_file = 'annotation_test.txt'
        paths = []
        texts = []
        with open(os.path.join(root_dir, paths_file), 'r') as fr:
            for line in fr.readlines():
                path, index_str = line.strip().split(' ')
                path = os.path.join(root_dir, path)
                paths.append(path)
                texts.append(index_str)
        return paths, texts
```
        
  Where instead of taking int of str I passed the index_str directly to the text.append. The training runs but accuracy looks 0.0. I was doubting the way I have created data. Would you mind giving me some advice here?
  
Note: I just trained for about 20 epochs, is is too early to say the accuracy is 0.0 or if I train it more there is probability of seeing some results?

**Comment by GitYCC** [comment]
plz reference: https://github.com/GitYCC/crnn-pytorch/wiki/Data-Format-of-MJSynth-(Synth90)
to prepare your dataset

**Comment by akshatsingh22** [comment]
Hi @GitYCC ,

Many thanks for your response...

Based on your input I changed lexicon and added index. But it was not converting char to label. For me the thing worked was keeping everything in small case in lexicon.txt and following the same thing you suggested. I'm good for now you can update your lexixon.txt in the link and maybe close the issue...thanks
