### ISSUE TITLE
Does it only do lowercase predictions?

### ISSUE THREAD

**Issue by akashlp27** [GitYCC/rcnn-pytorch#9]
Hey, thanks for the work, is there any parameter that I can change in order to get the predictions for capital letters....?, is it case sensitive or only lowercase ?

**Comment by GitYCC** [comment]
It's only lowercase currently.  
(https://github.com/GitYCC/crnn-pytorch/blob/master/src/dataset.py#L14)

You can change dataset to train your case sensitive model.
(https://github.com/GitYCC/crnn-pytorch/blob/master/src/dataset.py#L13)
